DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;

create table department
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name varchar(40),
    department_code varchar(10)
);

create table employee
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(30),
    surname       varchar(30),
    age           int,
    salary        decimal(8, 2),
    city          varchar(30),
    country       varchar(30),
    zipCode       varchar(10) check ( length(zipCode) < 10 )
);








